name: cardocai
description: A car fault diagnosis application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.11
  record: ^3.0.4
  audioplayers: ^3.0.1
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  image_picker: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  branding: assets/images/logo.png
  color_dark: "#000000"
  image_dark: assets/images/logo.png
  branding_dark: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/default_avatar.png
    - assets/images/flash_screen1.png
    - assets/images/flash_screen2.png
    - assets/images/flash_screen3.png
    - assets/images/google_icon.jpg
    - assets/images/CarFAULTDiagnosisAPP (2)/SEACRH.png
    - assets/images/CarFAULTDiagnosisAPP (2)/mechanic.png
    - assets/images/CarFAULTDiagnosisAPP (2)/record.png
    - assets/images/CarFAULTDiagnosisAPP (2)/fault.png 